---
inherit_gem:
  voxpupuli-test: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: '3.1'

Layout/LineLength:
  Max: 200

Layout/HashAlignment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - spec/acceptance/**/*.rb

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/WordArray:
  Enabled: false
